export default ACTION_TYPE = 'ACTION_TYPE';
export default ACTION_TYPE_SUCCESS = 'ACTION_TYPE_SUCCESS';
export default ACTION_TYPE_ERROR = 'ACTION_TYPE_ERROR';
export default ACTION_TYPE_LOADING = 'ACTION_TYPE_LOADING';
